import Header from "@/sharedComponents/Header";
import Footer from "@/sharedComponents/Footer";
import detectDevice from "@/utils/detectDevice";
import Styles from "./index.module.scss";
import ColorTitle from "@/sharedComponents/ColorTitle";
import FAQ from "@/pageSections/FAQ";

export default function TermsAndConditions({ data, isMobile }) {
  console.log("data", data, isMobile);

  return (
    <div id="root">
      <Header isMobile={isMobile} />
      <div className={Styles.container}>
        <ColorTitle text="Terms Of <span>Use</span>" />
        {data.map((item, idx) => {
          return (
            <div className={Styles.container__section} key={idx}>
              {item.title && <h3>{item.title}</h3>}
              <FAQ data={item} showTitle={false} />
              {item.disclaimer && <p>{item.disclaimer}</p>}
            </div>
          );
        })}
      </div>
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const userAgent = context.req.headers["user-agent"];
  const isMobile = detectDevice(userAgent);

  const data = [
    {
      title: "",
      faqs: [
        {
          question: "Non-Financial Returns",
          answer: `Altruvo Social Ventures Private Limited ("Altruvo") emphasizes that no financial returns, including but not limited to financial securities (debt or equity), interest, dividend, profit share, or cash rewards, are provided to individuals who contribute to our initiatives. Contributions made to Altruvo should not be construed as investments in any form whatsoever.`,
        },
        {
          question: "Electronic Record",
          answer: `This document serves as an electronic record in compliance with the Information Technology Act, 2000, with all amendments upto date and other relevant statutes, generated by our computer systems, it does not require physical or digital signatures.`,
        },
        {
          question: "Compliance with Regulations",
          answer: `Published in accordance with Rule 3 (1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021, this document outlines the terms of use for accessing or utilizing our website, www.altruvo.org.`,
        },
        {
          question: "Company Information",
          answer: `The domain name www.altruvo.org ("Website") is licensed for use by Altruvo Social Ventures Private Limited, an Indian company, duly incorporated under the Indian Companies Act, 2013. Our registered office is located at 1103, Akansha Opulence, Shakti Nagar, Kota - 324009.`,
        },
        {
          question: "Terms of Use",
          answer: `By accessing or transacting on our Website, you agree to the terms and conditions outlined herein, along with our applicable policies. Your use of the Website constitutes a binding agreement with Altruvo.`,
        },
        {
          question: "User Definition",
          answer: `In these Terms of Use, "you" or "User" refers to any natural or legal person, including both Donors/Contributors and Campaigners, who become members/users of the Website. Users may register on the Website or access it through Associated Partners (via the API). The term "we," "us," "our" denotes Altruvo, while "you" and "your" refer to the User.`,
        },
        {
          question: "Service Guidelines",
          answer: `Use of any services provided by Altruvo through the Website subjects you to the rules, guidelines, policies, terms, and conditions applicable to such services. We reserve the right to modify these Terms of Use without prior notice. It is your responsibility to review these terms periodically for updates and changes.`,
        },
      ],
      disclaimer: `Your acceptance and adherence to these Terms of Use signify your agreement to abide by the terms and conditions outlined herein, including compliance with the Altruvo Privacy Policy.`,
    },
    {
      title: "Services Offered by Altruvo",
      faqs: [
        {
          question: "Platform Facilitation",
          answer: `Altruvo Social Ventures Private Limited ("Altruvo") operates as a
            facilitator, providing a platform where individuals, organizations, and causes can connect.
            Our platform serves as a meeting ground for Users, including Donors/Contributors and
            Campaigners, enabling them to engage with a diverse range of initiatives and amplify their
            impact.`,
        },
        {
          question: "Interactive Environment",
          answer: `Altruvo fosters an interactive environment where Donors can
            discover and engage with various Campaigners and non-profit organizations. Through our
            platform, Donors have the opportunity to explore campaigns, evaluate causes, and
            participate in transactions, whether through contributions or information sharing. Altruvo
            respects the autonomy of Campaigners and aims to empower them to effectively convey
            their message and garner support.`,
        },
        {
          question: "Content Collaboration",
          answer: `Content creation in relation to campaigns is a collaborative
            effort between Altruvo and Campaigners. Whether sourced directly from Campaigners or
            developed in partnership with them, the content is tailored to promote and advocate for
            the Campaigns showcased on our platform. Altruvo operates transparently, ensuring that all
            content is presented with integrity and authenticity, reflecting the essence of each initiative.`,
        },
        {
          question: "Neutral Intermediary",
          answer: `Altruvo maintains a neutral stance in its role as an intermediary.
            While we provide a platform for Campaigners to showcase their initiatives and engage with
            potential supporters, we do not exert control or influence over individual campaigns.
            Altruvo respects the diversity of causes and perspectives represented on our platform,
            allowing Users to make informed decisions based on their interests and values.`,
        },
        {
          question: "Financial Neutrality",
          answer: `Altruvo upholds financial neutrality and transparency. We do not
            assert any rights or claims over funds or rewards contributed by Donors. Our commitment is
            to facilitate connections and empower social impact initiatives, without assuming ownership
            or responsibility for the outcomes of individual campaigns. Altruvo remains dedicated to
            fostering a supportive ecosystem where collaboration and collective action drive positive
            change.`,
        },
      ],
    },
    {
      title: "Eligibility of the User",
      faqs: [
        {
          question: "Legal Capacity",
          answer: `Use of the Altruvo platform is restricted to individuals who can
            form legally binding contracts under the Indian Contract Act, 1872. Persons deemed
            "incompetent to contract" as per the Indian Contract Act, 1872, including minors and
            un-discharged insolvents, are ineligible to use the Website. Minors, defined as
            individuals under the age of 18 years, are prohibited from registering as members on
            Altruvo or conducting transactions directly on the platform. If a minor wishes to
            engage with the Website, such actions must be undertaken by their legal guardian,
            parents, or through a competent organization/NGO. Altruvo reserves the right to
            terminate membership and deny access to the Website upon discovery of a User's
            underage status.`,
        },
        {
          question: "Organizational Registration",
          answer: `For Organizations/Entities or Legal Persons
            registering on the platform, representation implies authorization by the
            Organization/Entity Management to accept these Terms of Use and bind the
            Organization/Entity accordingly.`,
        },
      ],
    },
    {
      title: "Campaigner",
      faqs: [
        {
          question: "Qualifying Entities",
          answer: `Non-Profit Organizations registered in India, individuals
            supporting or advocating for such organizations, or Indian-based private limited
            companies are eligible to host campaigns on the Altruvo Website. Campaigners,
            encompassing Non-Profit Organizations, Individuals, or Indian companies registered
            with or affiliated with Altruvo, can initiate campaigns following the platform"s
            Policies and any associated agreements.`,
        },
        {
          question: "Accuracy and Truthfulness",
          answer: `Campaigners are legally obligated to furnish accurate,
            truthful, and complete information regarding the purpose and utilization of raised
            funds on our Website.`,
        },
        {
          question: "Transparency",
          answer: `Campaign descriptions must be clear and non-misleading,
            accurately portraying the need and intended use of raised funds. Altruvo reserves
            the right to remove campaigns deemed false, misleading, or not reflective of their
            true nature.`,
        },
        {
          question: "Document Authenticity",
          answer: `All documents and information submitted by
            Campaigners to Altruvo must be truthful, up-to-date, and relevant solely to the
            Campaign or beneficiary.`,
        },
        {
          question: "Intellectual Property Rights",
          answer: `Campaign listings must respect the intellectual
            property, trade secret, and proprietary rights of third parties. Offered rewards or
            promotions must be fulfilled as promised by the Campaigner.`,
        },
        {
          question: "Accountability",
          answer: `Campaigners are responsible for providing accurate progress
            reports and any necessary information to Donors regarding fund utilization.`,
        },
        {
          question: "Legal Compliance",
          answer: `Compliance with applicable laws, including but not limited to
            the Income Tax Act, 1961, and the Foreign Contributions Regulation Act, 2010, is
            mandatory for Campaigners. Ensuring the validity of licenses/permissions related to
            the Campaign throughout its duration is the Campaigner"s responsibility.`,
        },
        {
          question: "Integrity",
          answer: `Campaigners must promptly report any past or ongoing investigations
            or charges related to criminal activities, ensuring transparency and trust within the
            Altruvo community.`,
        },
        {
          question: "Disclosure",
          answer: `Full and timely disclosure of material facts concerning the
            beneficiary, purpose, and campaign is required. Any changes to provided
            information must be promptly communicated to Altruvo and Donors.`,
        },
        {
          question: "Information Accuracy",
          answer: `Altruvo reserves the right to suspend or terminate
            campaigns if provided information is inconsistent, inaccurate, or incomplete,
            ensuring platform integrity and Donor trust.`,
        },
        {
          question: "Funds Utilization",
          answer: `Campaigners must withdraw/utilize raised funds within 45
            days of the campaign"s end. Altruvo retains the right to refund/payout funds to
            beneficiaries if Campaigners fail to do so within the specified timeframe.`,
        },
        {
          question: "Tip Option",
          answer: `Campaigners have the option to leave a tip while withdrawing funds,
            acknowledging that Altruvo may utilize such tips at its discretion without obligation
            for refund.`,
        },
        {
          question: "Periodic Updates",
          answer: `Campaigners may be required to periodically update or attest
            to their eligibility to receive donations, including compliance with foreign donation
            laws.`,
        },
        {
          question: "Ethical Image Posting",
          answer: `<ul><li><b>Permission: </b>Campaigners must obtain permission
            from individuals depicted in campaign images and clarify usage intentions, especially
            if minors are involved.</li><li><b>Informed Consent: </b>Clarity on crowdfunding purposes and
            wide usage of images must be communicated transparently to all individuals
            depicted.</li><li><b>Authenticity: </b>Images should reflect authenticity and avoid portraying
            individuals in a demeaning or manipulated manner.</li><li><b>Child Protection: </b>Adherence
            to child protection guidelines, including nudity, manipulation, privacy, and respectful
            image selection, is mandatory.</li></ul>`,
        },
      ],
      disclaimer: `This adaptation ensures originality while encapsulating the essence and requirements for
      eligibility of users and campaigners on the Altruvo platform.`,
    },
    {
      title: "Donors",
      faqs: [
        {
          question: "Payment Agreement",
          answer: `Donors acknowledge and agree to adhere to the terms and
                conditions outlined herein regarding payments for any Campaign facilitated through
                the Altruvo platform.`,
        },
        {
          question: "Receipt of Updates",
          answer: `Donors consent to receiving timely updates regarding the
                progress/status of fundraisers via SMS and email from both the Campaigner and
                Altruvo. Opting out of this service can be managed by logging into the Donor's
                Altruvo profile and disabling communications for specific campaigns.`,
        },
        {
          question: "Information Access and Due Diligence",
          answer: `Donors have access to information about
                Campaigners and beneficiaries on the Website, including means of direct
                communication. However, Altruvo does not certify the accuracy, completeness, or
                warranty of any Campaign information provided. Donors are encouraged to conduct
                independent due diligence before making donations and should not solely rely on
                Altruvo for the accuracy or completeness of campaign information.`,
        },
        {
          question: "Non-Profit Organization Engagement",
          answer: `Donors contributing to campaigns listed
                on behalf of non-profit organizations in India shall approach the specific organization
                directly for tracking fund utilization or obtaining relevant information. Altruvo
                relinquishes accountability once funds are transferred to the respective non-profit
                organization.`,
        },
        {
          question: "Premature Campaign Termination",
          answer: `In cases of premature campaign termination,
                such as due to the Campaigner"s death or early recovery, unutilized donations may
                occur. Altruvo reserves the right to redirect unutilized funds to other active
                campaigns on the platform. Efforts will be made to redeploy these contributions
                within 45 days, with full refunds issued if redeployment is not feasible within the
                specified timeframe.`,
        },
        {
          question: "Authorization for Fund Processing",
          answer: `Donors authorize Altruvo and its service
                providers to collect, process, facilitate, and remit funds through standard banking
                channels, payment, clearance, and settlement systems.`,
        },
        {
          question: "Payment Processing Control",
          answer: `Altruvo reserves the right to delay or refuse
                payment processing for any Donor, including questionable transactions. This includes
                suspected collusion between Donors and Campaigners to deceive others, breach
                laws or policies, or engage in fraudulent activities.`,
        },
      ],
    },
    {
      title: "User Account and Registration Obligations",
      faqs: [
        {
          question: "Confidentiality Responsibility",
          answer: `Users are accountable for maintaining
                the confidentiality of their Login Name and Password, bearing responsibility for all
                activities occurring under their Login Name. Altruvo reserves the right to indefinitely
                suspend, terminate, or block access to a user's membership on the Website if
                provided information is inconsistent, inaccurate, incomplete, or does not comply
                with the Terms of Use.`,
        },
      ],
    },
    {
      title: "Communications",
      faqs: [
        {
          question: "Electronic Communication Consent",
          answer: `Users
                acknowledge that communication with Altruvo occurs through electronic records    
                and consent to receive communications via electronic records periodically and as
                required. Altruvo may communicate with users via email or other electronic modes.`,
        },
      ],
    },
    {
      title: "Platform for Information, Communication, and Transaction",
      faqs: [
        {
          question: "Independent Commercial/Contractual Terms",
          answer: `All commercial/contractual terms are solely between the Campaigner and
            Donors/Contributors. Altruvo does not engage in determining the details of
            campaigns or offers, or advise on, control, or involve itself in the
            commercial/contractual terms between Donors/Contributors and Campaigners.`,
        },
        {
          question: "Representation and Warranty Disclaimer",
          answer: `Altruvo does not make any
            representation or warranty regarding the specifics of campaigns on the Website,
            apart from expressly made representations for individual campaigns. Users are
            encouraged to independently verify the accuracy of statements on the Website and
            Altruvo accepts no liability for errors or omissions.`,
        },
        {
          question: "Responsibility Disclaimer",
          answer: `Altruvo is not responsible for non-performance or
            under-performance of commitments made by Campaigners or for any contractual
            obligations entered into between Contributors and Campaigners. Ketto does not
            guarantee the performance of any commitment made on the Website and is not
            obligated to mediate disputes between Donors and Campaigners. However, Altruvo
            welcomes feedback and grievances from Users for improvement of the Website's
            user experience.`,
        },
        {
          question: "Campaigner Verification Recommendation",
          answer: `Users are advised to independently
            verify the authenticity of Campaigners before donating or contributing on the
            Website and to exercise their best judgment in this regard.`,
        },
      ],
    },
    {
      title: "Charges",
      faqs: [
        {
          question: "Fee Structure",
          answer: `Altruvo's platform allows users to browse without
            any charges. However, Altruvo levies a facilitation fee, including platform/collection
            fees and transactional charges, which are borne by the beneficiaries of funds raised
            on the platform. These charges are based on mutually agreed terms and conditions
            between Altruvo and the beneficiaries. Altruvo reserves the right to modify its Fee
            Policy, introducing new services or amending existing ones at its sole discretion.`,
        },
        {
          question: "Agreement to Pricing Policy",
          answer: `By agreeing to the Terms of Use, users consent to
            Altruvo's plans and pricing policy.`,
        },
        {
          question: "Advertising Campaign Charges",
          answer: `Altruvo conducts advertising campaigns on
            behalf of its campaigners, deducting the full advertising expense, along with the
            facilitation fee, before transferring the funds to the beneficiary.`,
        },
      ],
    },
    {
      title: "General Rules for the Use of the Platform",
      faqs: [
        {
          question: "Prohibited Content",
          answer: `Users are prohibited from hosting, displaying, uploading, modifying, publishing, transmitting, or sharing any information that infringes upon the rights of others, contains misleading or offensive content, promotes illegal activities, or violates any law or regulation. This includes content that is harassing, defamatory, obscene, or promotes illegal conduct.`,
        },
        {
          question: "Unauthorized Access and Activities",
          answer: `Users agree not to engage in unauthorized access to the Altruvo platform or its systems, including attempting to circumvent security measures or interfere with the proper functioning of the platform.`,
        },
        {
          question: "Data Protection and Misuse",
          answer: `Users shall not probe, scan, or test the vulnerability of the platform or its networks, nor shall they manipulate identifiers or exploit the platform for unlawful purposes. Users are responsible for ensuring compliance with applicable laws, including data protection regulations.`,
        },
        {
          question: "Indemnification",
          answer: `Users indemnify Altruvo against liabilities, claims, losses, and damages arising from their actions or omissions, including misuse of funds, provision of false information, or breach of applicable laws. This indemnification extends beyond the duration of the Terms of Use.`,
        },
        {
          question: "Monitoring and Content Removal",
          answer: `Altruvo reserves the right to monitor and remove content that violates the Terms of Use. However, users remain solely responsible for the content they post on the platform.`,
        },
        {
          question: "Dealings with Advertisers",
          answer: `Users engage in business dealings with advertisers at their own risk, and Altruvo disclaims any liability for losses incurred as a result of such dealings.`,
        },
        {
          question: "Exposure to Offensive Materials",
          answer: `Users acknowledge the possibility of exposure to offensive materials posted by others on the platform and agree that Altruvo is not responsible for such content.`,
        },
        {
          question: "DoS/DDoS Involvement",
          answer: `Users understand that involvement in DoS/DDoS attacks may result in necessary actions and claims for damages by Altruvo.`,
        },
        {
          question: "Changes to Terms of Use",
          answer: `Altruvo reserves the right to modify the Terms of Use, with notice provided to users. Continued use of the platform constitutes acceptance of the revised terms.`,
        },
        {
          question: "Service Description",
          answer: `Altruvo's platform serves as a fundraising tool, facilitating transactions between Campaigners and Donors. Altruvo is not a party to any agreement between users and disclaims liability for the conduct of users or the outcome of fundraising efforts. Users must independently verify the accuracy of information provided through the platform.`,
        },
        {
          question: "Background Checks and Authorization",
          answer: `Users authorize Altruvo to conduct background checks and obtain information about them and beneficiaries. Users release Altruvo from any claims arising from such investigations.`,
        },
      ],
    },
    {
      title: "Content Posted on Altruvo",
      faqs: [
        {
          question: "Third-Party User-Generated Content",
          answer: `All text, graphics, user interfaces, visual interfaces, photographs, videos, interviews, pictures, speech, trademarks, logos, sounds, music, and artwork (collectively, "Content") generated by third-party users are considered third-party user-generated content. Altruvo does not control this content, acting merely as an intermediary under these Terms of Use.`,
        },
        {
          question: "Restrictions on Use",
          answer: `Except as expressly provided in these Terms of Use, no part of the Altruvo website and no content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, or distributed in any way (including "mirroring") to any other computer, server, website, or other medium for publication or distribution or for any commercial enterprise without Altruvo's express prior written consent.`,
        },
      ],
    },
    {
      title: "Limited License",
      faqs: [
        {
          question: "Campaigner License",
          answer: `Altruvo grants campaigners a limited, non-transferable, non-
          exclusive, non-sublicensable, non-assignable, and personal license to use "Funds raised
          through Altruvo," "Powered by Altruvo," and/or "via Altruvo" names and/or logos on
          campaigners' invoices or certificates of donation for transactions concluded on the
          platform. Additionally, Altruvo grants campaigners a limited, non-transferable, non-
          exclusive, non-sublicensable, non-assignable, and personal license to use the "Altruvo.org"
          name and/or logo on stationery used by the campaigner for delivery of communications,
          receipts, certificates, etc., through the platform.`,
        },
      ],
    },
    {
      title: "Linked Websites / APIs / Social Networking Sites",
      faqs: [
        {
          question: "Third-Party Links",
          answer: `Altruvo does not assume responsibility or liability for the actions, products, content, and services on the platform that are linked to affiliates and/or third-party websites using the platform's APIs or otherwise. Altruvo may provide links to third-party websites of affiliated companies and certain other businesses, but it does not warrant or endorse the offerings, content, or services of these businesses or individuals.`,
        },
        {
          question: "External Sites and Resources",
          answer: `The services may provide or facilitate, or third parties may provide, links or other access to other sites, services, and resources on the Internet. Altruvo does not control these sites, services, and resources and is not responsible for or does not endorse them. You acknowledge and agree that Altruvo will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, events, goods, or services available on or through any such site, service, or resource.`,
        },
        {
          question: "Third-Party Interactions",
          answer: `Any dealings you have with third parties found while using the services are between you and the third party. You agree that Altruvo is not liable for any loss or claim that you may have against any such third party.`,
        },
        {
          question: "Social Networking Services",
          answer: `You may enable or log into the services via various online third-party services, such as social media and social networking services like Facebook or Twitter ("Social Networking Services"). By logging in or directly integrating these Social Networking Services into the services, your online experiences may be enriched and more personalized. We may ask you to authenticate, register for, or log into Social Networking Services on their respective providers' websites. As part of such integration, these services will provide us with access to certain information you have provided to them, which we will use, store, and disclose in accordance with our Privacy Policy. Please note that the use, storage, and disclosure of your information by these Social Networking Services are governed solely by their policies, and Altruvo is not liable for the privacy practices or other actions of any third-party site or service that may be enabled within the services.`,
        },
        {
          question: "Accuracy and Reliability",
          answer: `Altruvo is not responsible for the accuracy, availability, or reliability of any information, content, goods, data, opinions, advice, or statements made available in connection with Social Networking Services. Altruvo is not liable for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such Social Networking Services. These features are provided merely as a convenience, and their inclusion does not imply endorsement or recommendation.`,
        },
      ],
    },
    {
      title: "Privacy",
      faqs: [
        {
          question: "Privacy Protection",
          answer: `Protecting your privacy is a core principle for Altruvo. We clearly
          understand that your personal information is one of our most important assets. We store
          and process your information, including any sensitive personal information or data
          collected, on computers protected by physical and reasonable technological security
          measures and procedures in accordance with applicable laws and regulations. Our current
          Privacy Policy is available <a href="/privacy-policy">here</a>. If you object to your information being transferred or used in
          this manner, please do not use the platform.`,
        },
      ],
    },
    {
      title: "Disclaimer of Warranties and Liability",
      faqs: [
        {
          question: "General Disclaimer",
          answer: `The Altruvo platform, all materials, information (including but not limited to campaigns), and services included or otherwise made available to you through this site are provided on an "as is" and "as available" basis without any representations or warranties, express or implied, except as otherwise specified in writing. Altruvo does not warrant that the platform will be constantly available or available at all, nor that the information on the platform is complete, true, accurate, or non-misleading.`,
        },
        {
          question: "Limitation of Liability",
          answer: `Altruvo will not be liable to you in any way in relation to the contents of, use of, or otherwise in connection with, the platform. Nothing on the platform constitutes, or is meant to constitute, advice of any kind.`,
        },
        {
          question: "Communication Consent",
          answer: `You will be required to enter a valid phone number and email address when making a donation/contribution on the platform. By registering your phone number and email address with us, you consent to be contacted by us and/or the campaigner via phone calls and/or SMS notifications regarding any reward or delivery-related updates. We will not use your personal information to initiate any promotional phone calls or SMS without your consent. YOUR USE OF THE SERVICE IS AT YOUR SOLE RISK.
          ALTRUVO AND ITS AFFILIATES EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. ALTRUVO AND ITS AFFILIATES MAKE NO WARRANTY THAT (I) THE SERVICE WILL MEET YOUR REQUIREMENTS, (II) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, OR (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS.`,
        },
      ],
    },
    {
      title: "Financial Transaction Facility - Donors / Contributors",
      faqs: [
        {
          question: "Transaction Authorization",
          answer: `When using any payment/donation/contribution methods
            available on the Altruvo website, we are not responsible for any loss or damage arising
            directly or indirectly due to:<ul><li>Lack of authorization for any transactions</li><li>Exceeding the preset limit mutually agreed by you and your bank(s)</li><li>Any payment issues arising from the transaction</li><li>Decline of transaction for any other reasons</li></ul>`,
        },
        {
          question: "Currency and Payment Gateways",
          answer: `All payments made towards donations/contributions on the Altruvo website by Indian nationals using Indian payment gateways must be in Indian Rupees (INR). Payments in any other currency must be processed through the Foreign Payment Gateway. The website will not facilitate transactions through the Indian Payment Gateway for donations/contributions made by non-Indian nationals.`,
        },
        {
          question: "Authorization to Collect Payments",
          answer: `By using the payment facility, you authorize Altruvo or its service providers (e.g., payment gateways, banks, and marketplace settlement providers like PayU, Razorpay, Stripe, Billdesk, Paytm, HDFC Bank, RBL Bank, Gocashfree) to collect, process, facilitate, and remit payments electronically. Altruvo is an independent contractor and is not liable for the campaigns listed on the website where money is transacted using the payment facility.`,
        },
        {
          question: "Nature of Payment Facility",
          answer: `The payment facility provided by Altruvo is not a banking or financial service but a facilitator providing electronic, automated online payment, collection, and remittance facility for transactions on the website. Altruvo is not acting as a trustee or in a fiduciary capacity with respect to the transaction or the transaction price.`,
        },
        {
          question: "Refusal of Transactions",
          answer: `Altruvo reserves the right to refuse to process transactions by donors/contributors with a history of questionable transactions, including collusion between donor and campaigner to mislead others or violate any law or policy.`,
        },
        {
          question: "Suspicious Transactions",
          answer: `Altruvo may delay notifying the payment/transaction confirmation if deemed suspicious. In such cases, Altruvo may hold the transaction amount and inform law enforcement officials instead of refunding the amount to the donor, if the donor/contributor or campaigner is engaged in illegal activity.`,
        },
        {
          question: "Non-liability for Transaction Processing",
          answer: `Altruvo is not liable for any damages, interests, or claims resulting from the non-processing or delay in processing a transaction/transaction price beyond its control.`,
        },
        {
          question: "Discharge of Liability",
          answer: `Altruvo will make payments, net of costs, charges, and fees, into the bank account provided by the campaigner during registration. Once payments are made into the provided bank account, Altruvo is discharged of any liability towards the campaigner and donors/contributors, who are not eligible for claims or refunds.`,
        },
        {
          question: "Refund",
          answer:
            "Refunds will be issued to donors, less any applicable transaction fees, in the event that a campaign does not meet its funding target, and will be processed in accordance with the settlement cycle of the payment gateway.",
        },
      ],
    },
    {
      title: "Financial Transaction Facility - Campaigner",
      faqs: [
        {
          question: "Registration and Information",
          answer: `Campaigners must register with Altruvo and provide necessary information, including banking details, PAN, and registration certificates as required by law. Campaigners must fulfill commitments to donors/contributors as detailed in the campaign in a timely manner. Altruvo may seek information about fund usage even after the campaign ends and provide details to donors/contributors.`,
        },
        {
          question: "Fund Transfer",
          answer: `Funds collected for each campaign will be transferred to the campaigner (net of Altruvo fees, payment gateway charges, and applicable taxes) within 15 days of campaign completion or as per withdrawal request. If unable to fulfill commitments, campaigners must return the money to donors/contributors promptly.`,
        },
        {
          question: "Remittance Compliance",
          answer: `Remittances to campaigners for successful transactions will comply with directions issued by the Reserve Bank of India. Cheque donations/contributions will be remitted via cheque/demand draft or online bank transfer to the campaigner’s bank account.`,
        },
        {
          question: "Net Settlements",
          answer: `Altruvo will settle all amounts net of its fees to the campaigner’s accounts per applicable guidelines from the Reserve Bank of India.`,
        },
        {
          question: "Chargebacks",
          answer: `If a chargeback occurs on a transaction already transferred to the campaigner/beneficiary, the campaigner/beneficiary must refund the amount charged back to Altruvo.`,
        },
      ],
    },
    {
      title: "Compliance with Laws",
      disclaimer: `Donors/contributors must comply with all applicable laws, including the Foreign Exchange
        Management Act, 1999, Information Technology Act, 2000, Prevention of Money
        Laundering Act, 2002, Foreign Contribution Regulation Act, 2010, Income Tax Act, 1961, and
        Export Import Policy of India, while using the payment facility and website.`,
    },
    {
      title: `Donor's / Contributors Arrangement with Issuing Bank`,
      faqs: [
        {
          question: "Card Payments",
          answer: `All valid credit/debit/cash cards and other payment instruments are processed using a card payment gateway or appropriate payment system infrastructure, governed by the terms agreed between the donor/contributor and the issuing bank/payment instrument company.`,
        },
        {
          question: "Bank Transfers",
          answer: `All online bank transfers are processed using the gateway provided by the respective issuing bank, governed by the terms agreed between the donor/contributor and the issuing bank.`,
        },
      ],
    },
    {
      title: "Breach",
      faqs: [
        {
          question: "Actions for Breach",
          answer: `We may limit your activity, remove your information, warn other users of your actions, suspend or terminate your membership, and/or refuse you access to the website if you breach the Terms of Use or Privacy Policy, fail to verify or authenticate information, or cause legal liability.`,
        },
        {
          question: "Reinstatement",
          answer: `Suspended users may be reinstated at our discretion. Suspended or blocked users may not register or use the website until reinstated. We reserve the right to recover amounts due and take legal action, including referring to authorities for criminal proceedings, for any breach of Terms of Use or Privacy Policy.`,
        },
      ],
    },
    {
      title: "Indemnity",
      faqs: [
        {
          question: "Campaigner Indemnity",
          answer: `Campaigners must indemnify and hold Altruvo, its affiliates, and their officers, directors, agents, and employees harmless against all claims, penalties, prosecutions, losses, costs, and expenses, including reasonable attorney's fees, arising from any breach, negligence, or violation of any law or rights of a third party.`,
        },
        {
          question: "User Indemnity",
          answer: `You agree to release, indemnify, and hold Altruvo and its affiliates and their officers, employees, directors, and agents harmless from any losses, damages, expenses, rights, claims, actions, and injury (including death) arising from your use of the services, any donation, any campaign, any user content, your connection to the services, your violation of these Terms of Use, or your violation of any rights of another.`,
        },
      ],
    },
    {
      title: "",
      faqs: [
        {
          question: "Waiver",
          answer: `<ol><li><b>Service Provider Role:</b> The User acknowledges that Altruvo acts solely as a service provider, facilitating nonprofit organizations and campaigners in India to promote their causes. Altruvo is not liable for any misrepresentation or inaccuracies in the information provided by the campaigners.</li></ol>`,
        },
        {
          question: "Modifications and Alterations",
          answer: `<ol><li><b>Service Access:</b> The User can use Altruvo's services according to the terms specified in the Terms of Use and any other relevant agreements. Altruvo reserves the right to make modifications to these terms.</li><li><b>User Obligations:</b> Users are required to comply with any changes to the terms, conditions, and regulations set forth by Altruvo.</li></ol>`,
        },
        {
          question: "Intellectual Property Rights",
          answer: `<ol><li><b>Content Protection:</b> Users acknowledge that Altruvo's services may include content protected by intellectual property laws. Users must not modify, copy, or distribute this content without authorization.</li><li><b>Prohibited Actions:</b> Users are prohibited from engaging in data mining or other unauthorized data extraction methods. Circumventing access restrictions imposed by Altruvo is also forbidden.</li><li><b>Software Rights:</b> The software underlying Altruvo's services is owned by Altruvo and its partners. Users are not permitted to reverse engineer or redistribute this software.</li></ol>`,
        },
        {
          question: "User Content",
          answer: `<ol><li><b>Content Ownership:</b> Users retain ownership of the content they upload but grant Altruvo a license to use this content for service operation and promotion.</li><li><b>Warranties and Releases:</b> Users represent that they have the necessary rights to the content they upload and release Altruvo from any claims related to the use of this content.</li></ol>`,
        },
        {
          question: "Dispute Resolution",
          answer: `<ol><li><b>Arbitration Agreement:</b> Disputes involving Altruvo will be resolved through arbitration in Mumbai, under Indian law. This includes any claims arising before or after the termination of the Terms of Use.</li><li><b>Scope of Arbitration:</b> The arbitration agreement covers a wide range of claims, including those based on contract, tort, and other legal theories.</li></ol>`,
        },
        {
          question: "Limitation of Liability",
          answer: `<ol><li><b>Liability Cap:</b> Altruvo is not liable for indirect, incidental, or consequential damages. The total liability is capped at the amount paid by the user to Altruvo in the last six months or INR 2000, whichever is greater.</li><li><b>Exclusive Remedy:</b> Users dissatisfied with the service may discontinue its use as the sole and exclusive remedy.</li></ol>`,
        },
        {
          question: "Compliance",
          answer: `<ol><li><b>Anti-Money Laundering (AML):</b> Altruvo complies with AML guidelines set by the Reserve Bank of India. Campaign organizers must verify their identity and comply with foreign exchange and tax laws.</li><li><b>Identity Verification:</b> Campaign organizers must verify their identity using documents recognized by the Reserve Bank of India. Failure to comply may result in campaign cancellation and fund return to donors.</li></ol>`,
        },
        {
          question: "Termination",
          answer: `<ol><li><b>Account Suspension:</b> Altruvo may suspend or terminate user accounts for any reason, including inactivity or violation of terms. Altruvo can also discontinue services without notice.</li><li><b>Content Removal:</b> Altruvo may remove user content and deactivate accounts immediately, with no liability for termination.</li></ol>`,
        },
        {
          question: "User Disputes",
          answer: `<ol><li><b>Inter-User Responsibility:</b> Users are solely responsible for their interactions with other users. Altruvo has no liability in user disputes but may intervene at its discretion.</li></ol>`,
        },
        {
          question: "General Provisions",
          answer: `<ol><li><b>Entire Agreement:</b> The Terms of Use constitute the entire agreement between the user and Altruvo, superseding any prior agreements.</li><li><b>Additional Terms:</b> Users may be subject to additional terms when using third-party services.</li><li><b>No Waiver:</b> Altruvo's failure to enforce any provision is not a waiver of its rights.</li><li><b>Severability:</b> If any provision is found invalid, the remaining provisions remain in effect.</li><li><b>Statute of Limitations:</b> Claims related to the service must be filed within one year.</li><li><b>Assignment:</b> Users cannot assign the agreement without Altruvo's consent, but Altruvo can assign it without restriction.</li><li><b>Privacy Policy:</b> By using the services, users consent to Altruvo's collection and use of personal data as outlined in its Privacy Policy. Users also agree to be contacted via various communication modes.</li></ol>`,
        },
        {
          question: "Contact Us",
          answer: `Please send any questions regarding this website to workaltruvo@gmail.com`,
        },
      ],
    },
  ];

  //   {
  //     title: "Communications",
  //     faqs: [
  //       {
  //         question: "Electronic Communication Consent",
  //         answer: `Users
  //               acknowledge that communication with Altruvo occurs through electronic records
  //               and consent to receive communications via electronic records periodically and as
  //               required. Altruvo may communicate with users via email or other electronic modes.`,
  //       },
  //     ],
  //   },

  // Pass data to the page via props
  return { props: { data, isMobile } };
}
